# Generated by Django 5.0.6 on 2024-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=40)),
                ('dia', models.DateField()),
                ('hora', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('codigo_viaje', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['codigo_viaje', 'nombre_tutor'],
            },
        ),
        migrations.RenameModel(
            old_name='Crear_Viaje',
            new_name='Viaje',
        ),
        migrations.AlterModelOptions(
            name='participar',
            options={'ordering': ['codigo_viaje', 'apellido', 'nombre'], 'verbose_name': 'Participar', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='registrarse',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['codigo_viaje', 'nombre_tutor']},
        ),
    ]
