# Generated by Django 5.0.6 on 2024-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0002_viajeupdate_rename_crear_viaje_viaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Registrarse',
        ),
        migrations.DeleteModel(
            name='ViajeUpdate',
        ),
    ]
